name: Testing

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      chroma-no-auth:
        image: chromadb/chroma
        ports:
          - 8080:8000

      chroma-with-auth:
        image: chromadb/chroma
        ports:
          - 8081:8000
        env:
            CHROMA_SERVER_AUTHN_CREDENTIALS: authToken
            CHROMA_SERVER_AUTHN_PROVIDER: chromadb.auth.token_authn.TokenAuthenticationServerProvider

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13 cmake libssl-dev

    - name: Set GCC 13 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build -C Release --output-on-failure
